### PR TITLE
multiple changes

### PR DESCRIPTION
**Pull request by ikudosi**
Proposing the following changes:

- Update BullMQ version to latest
- Allow `queue:listen` to pass multiple queues to listen (ex: `queue:listen --queue:default,somethingelse`)
- Allow the native BullMQ `jobs.attempts` option to be respected. The handle method was encapsulated in a try/catch thus cannot honor retry.
- Allow calling a `failed()` from the job class when max attempts has succeeded and function exists.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Wow, thanks!

I need to add some tests to avoid manual testing. 😓 
I will play a bit with your PR.

What do you think of adding more documentation inside the `README` file for people not familiar with Queues and BullMQ?

**Comment by ikudosi** [comment]
@RomainLanz did my best to add to the readme. This is honestly my first ever attempt at contributing to any repo so bare with me xD. Hopefully all goes well on your end!

**Comment by RomainLanz** [comment]
> @RomainLanz did my best to add to the readme. This is honestly my first ever attempt at contributing to any repo so bare with me xD. Hopefully all goes well on your end!

No worries!

It seems that you aren't passing the `Job` instance when instantiating the requested `job`.

**Comment by ikudosi** [comment]
@RomainLanz adjusted the code so that the job instance is passed to the processor.

**Comment by RomainLanz** [comment]
Sorry for the delay, and thanks for the changes. I will have a look later today!

**Comment by RomainLanz** [comment]
Thanks! ❤️

**Pull request merged**
