### PR TITLE
Add support for `attempts` and `backoff`

### PR DESCRIPTION
**Pull request by KABBOUCHI**
Added `QueueScheduler` to support many BullMQ features, like `attempts` and `backoff`

image

### CODE REVIEW

**Comment by RomainLanz** [comment]
Thanks for the PR!

I have to read a bit more about it before merging, I would like to understand how it works before merging. 👍🏻

**Comment by RomainLanz** [comment]
Looking at `BullMQ` documentation, it seems that `QueueScheduler` is not needed anymore.

> From BullMQ 2.0 and onwards, the QueueScheduler is not needed anymore, so the information below is only valid for older versions.

https://docs.bullmq.io/guide/queuescheduler

**Comment by KABBOUCHI** [comment]
> Looking at `BullMQ` documentation, it seems that `QueueScheduler` is not needed anymore.
> 
> > From BullMQ 2.0 and onwards, the QueueScheduler is not needed anymore, so the information below is only valid for older versions.
> 
> [docs.bullmq.io/guide/queuescheduler](https://docs.bullmq.io/guide/queuescheduler)

yes, you can ignore this PR and release a new major version with bullmq 2.0 support

**Comment by RomainLanz** [comment]
Done in https://github.com/setten-io/adonis-bull-queue/pull/15

**Pull request closed without merging**
